version: "3"

services:
  backend:
    build: ../job-hunting-ai-backend
    ports:
      - "5001:5000"
    volumes:
      - ../job-hunting-ai-backend:/app
    environment:
      FLASK_ENV: development

  frontend:
    build: ../job-hunting-ai-frontend
    ports:
      - "3001:3000"
    volumes:
      - ../job-hunting-ai-frontend:/app
    environment:
      CHOKIDAR_USEPOLLING: "true"
